### ISSUE TITLE
Update `v2` tag in examples repo

### ISSUE THREAD

**Issue by Mierdin** [oreilly-npa-book/examples#10]
The examples links were all updated in [#39](https://github.com/oreilly-npa-book/orm-npa-deux/issues/39) to use the `v2` tag. Once we are ready to ship the book, we should close out any remaining changes to the examples repository, and ensure this tag reflects the most recent changes.

**Comment by Mierdin** [comment]
I just did this, as this was raised in copyedit (ch13 was missing from this tag). Will leave this issue open for now in case we want to make further changes, but as of now, v2 points to the latest commit in main.

**Comment by chadell** [comment]
@Mierdin I have updated `main` with two branches. Any problem to update `v2` tag to the latest commit in `main`?

**Comment by Mierdin** [comment]
No problem - please do this. Generally we should ensure the `v2` tag always points to the latest commit, until a third edition of the book exists, if that ever happens.

**Comment by chadell** [comment]
Update to latest commit in`main` and book updated
